export const DISPLAY_COUNTRY = 'DISPLAY_COUNTRY';
export const DISPLAY_ALL_COUNTRIES = 'DISPLAY_ALL_COUNTRIES';
export const DISPLAY_CONTINENT = 'DISPLAY_CONTINENT';
export const COUNTRY_DETAILS = 'COUNTRY_DETAILS';
export const REMOVE_COUNTRY = 'REMOVE_COUNTRY';
export const POST_ACTIVITY = 'POST_ACTIVITY';